from pypdf import PdfReader
import json, re, os

base = r'C:\Users\jeeva\Desktop\GIIPS-opencode'
json_path = os.path.join(base, r'ai-engine\data\ccmc_officer_directory.json')
pdf2_path = os.path.join(base, r'c_1\ccmc.gov.in\img\upload\Property_Tax_-_Top_Defualters_List1.pdf')

r2 = PdfReader(pdf2_path)
# Join all pages with clear separators
full = ''
for page in r2.pages:
    full += page.extract_text() + '\n'

# Split into entries at the page-break boundaries
# Each entry starts with: \nN WARD-XXX where N is serial number
# Remove header noise first
full = re.sub(r'S\.No\..*?K=\s*H\+I\n', '', full)
full = re.sub(r'Balance\n', '', full)
full = re.sub(r'TOTAL.*', '', full)
full = re.sub(r'Generated By.*', '', full)
full = re.sub(r'Page \d+ of \d+', '', full)

defaulters = []
# Find all entries: serial_number WARD-NNN
entries = re.finditer(r'(\d+)\s+WARD-(\d{3})(.*?)(?=\d+\s+WARD-\d{3}|\Z)', full, re.DOTALL)

for m in entries:
    serial = int(m.group(1))
    ward = int(m.group(2))
    rest = m.group(3).strip()
    
    # Find phone number - 10 digits
    phones = re.findall(r'(\d{10})', rest)
    if not phones:
        continue
    
    # Find zone
    zone_m = re.search(r'(NORTH|SOUTH|EAST|WEST|CENTRAL)\s+ZONE', rest)
    zone = zone_m.group(1) if zone_m else 'UNKNOWN'
    
    phone = phones[0]
    
    # Find where the phone appears in the text
    phone_pos = rest.find(phone)
    
    # Everything before the phone (minus zone) is the owner name
    before_phone = rest[:phone_pos].strip()
    # Remove WARD-NNN continuation (assessment numbers)
    before_phone = re.sub(r'^\d+/\d+/[\d/-]+\s*', '', before_phone)
    before_phone = re.sub(r'^[\d/\-]+\s*', '', before_phone)
    before_phone = before_phone.strip()
    
    # Everything after the phone up to the zone is the address
    after_phone = rest[phone_pos + len(phone):]
    zone_pos = after_phone.find(zone + ' ZONE') if zone != 'UNKNOWN' else -1
    if zone_pos >= 0:
        address = after_phone[:zone_pos].strip()
    else:
        address = after_phone.strip()
    # Clean address
    address = re.sub(r'\s+', ' ', address).strip()
    address = re.sub(r'^[\d\s,\-/]+', '', address).strip()
    address = re.sub(r'\s+', ' ', address).strip()[:200]
    
    # Clean owner name - remove trailing garbage
    owner_name = re.sub(r'\s+', ' ', before_phone).strip()
    # Remove trailing commas, dots, dashes
    owner_name = owner_name.rstrip(',.-').strip()
    
    if owner_name:
        defaulters.append({
            'ward_number': ward,
            'owner_name': owner_name[:150],
            'phone': phone,
            'zone': zone,
            'address': address,
            'source': 'property_tax_defaulter_list_2025-26'
        })

with open(json_path, 'r', encoding='utf-8-sig') as f:
    data = json.load(f)

data['property_tax_defaulters'] = defaulters

with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)

print(f'Parsed {len(defaulters)} defaulters')

# Show some samples from different zones
from collections import Counter
zones = Counter(d['zone'] for d in defaulters)
print(f'Zone breakdown: {dict(zones)}')

for d in defaulters[:8]:
    print(f'  #{d["ward_number"]:3d} ({d["zone"]}): {d["owner_name"][:35]:35s} {d["phone"]}  {d["address"][:40]}')
print('...')
for d in defaulters[-5:]:
    print(f'  #{d["ward_number"]:3d} ({d["zone"]}): {d["owner_name"][:35]:35s} {d["phone"]}  {d["address"][:40]}')
